### ISSUE TITLE
no model file 

### ISSUE THREAD

**Issue by augmen** [hitvoice/DrQA#13]
I run the command `python interact.py` got this error
`(pt) swapnilbhadade@hitvoice:~/pt/DrQA-1$ python interact.py
Traceback (most recent call last):
  File "interact.py", line 22, in <module>
    checkpoint = torch.load(args.model_file)
  File "/home/swapnilbhadade/pt/lib/python3.5/site-packages/torch/serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/best_model.pt'`

**Comment by hitvoice** [comment]
You need to download SQuAD and train the model first. Pretrained models are not provided currently.

**Comment by augmen** [comment]
ok
