### ISSUE TITLE
msgpack.exceptions.UnpackValueError: Unpack failed: error = 0

### ISSUE THREAD

**Issue by SamratSahoo** [hitvoice/DrQA#29]
I followed all of the instructions and then got this error. Would anyone know how to go about troubleshooting this?

`msgpack.exceptions.UnpackValueError: Unpack failed: error = 0`

Complete Error Message:

```
Traceback (most recent call last):
  File "/home/samrat/Documents/StudyBuddy/Algorithms/DrQA/interact.py", line 36, in <module>
    meta = msgpack.load(f, encoding='utf8')
  File "/home/samrat/Documents/StudyBuddy/venv/lib/python3.6/site-packages/msgpack/__init__.py", line 58, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 211, in msgpack._unpacker.unpackb
msgpack.exceptions.UnpackValueError: Unpack failed: error = 0

```
Just FYI, I trained the model in Google Colab and downloaded it from there. Could this have caused any problems? I ran interact.py in Colab and it worked fine so I am really unsure what the problem is.

Thank You in Advance!!

**Comment by SamratSahoo** [comment]
Turns out I also needed to download the `meta.msgpack` and `data.msgpack` files from Colab.
